version: "3.3"

services:
  mongodb:
    image: mongo-with-check:3.6
    # hostname: "${DB_HOSTNAME}"
    restart: unless-stopped
    container_name: mongodb-server
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME="${DB_USER}"
    #   - MONGO_INITDB_ROOT_PASSWORD="${DB_PASSWORD}"
    # command: [--auth]
    ports:
      - ${props["DB_PORT"]}:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
    container_name: backend
    restart: unless-stopped
    # volumes:
    #   - ./todo/:/usr/src/app
    #   - /usr/src/app/node_modules
    ports:
      - ${props["SERVER_PORT"]}:5001
    links:
      - mongodb
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    # command: npm start
    # volumes:
    #   - ./client/:/usr/app
    #   - /usr/app/node_modules
    ports:
      - ${props["CLIENT_PORT"]}:3000
    links:
      - backend
    depends_on:
      - backend

volumes:
  mongodb_data:


