version: "3.3"

services:
  mongodb:
    image: ${DB_IMAGE}
    restart: unless-stopped
    env_file:
      - .env
    container_name: mongodb-server
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  multi:
    image: ${APP_IMAGE}
    container_name: multi
    restart: unless-stopped
    env_file:
      - .env

    ports:
      - 5001:5001
      - 8084:8084
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data:


